"use client";

import { 
  TrendingUp, TrendingDown, Target, CreditCard, 
  Percent, DollarSign, BarChart2, Info, Package, ReceiptText, Calendar, FileText 
} from 'lucide-react';
import { cn } from '@/lib/utils';
import Amt from '@/components/Amt';

interface KPIProps {
  totalNet: number;
  totalTarget: number;
  achievement: number;
  costPercentage: number;
  totalCost: number;
  avgDiscountPercentage: number;
  totalValDisc: number;
  mtdGrowthPct: number;
  storeNetExcHO: number;
  annualSalesExcHO: number;
  annualTarget: number;
  annualAchievement: number;
  year: string;
  momGrowthPct: number;
  
  ytdQtyCurrent: number;
  ytdQtyPrevYear: number;
  ytdTxCurrent: number;
  ytdTxPrevYear: number;
  mtdQtyCurrent: number;
  mtdQtyPrevMonth: number;
  mtdTxCurrent: number;
  mtdTxPrevMonth: number;
}

const fmtPct = (n: number) => n.toFixed(1) + '%';

export default function KPICards(props: KPIProps) {
  const {
    totalNet, achievement, costPercentage, totalCost,
    avgDiscountPercentage, totalValDisc, mtdGrowthPct,
    storeNetExcHO, annualSalesExcHO, annualTarget, annualAchievement, year, momGrowthPct,
    ytdQtyCurrent, ytdQtyPrevYear, ytdTxCurrent, ytdTxPrevYear,
    mtdQtyCurrent, mtdQtyPrevMonth, mtdTxCurrent, mtdTxPrevMonth
  } = props;

  return (
    <div className="space-y-4">
      {/* Row 1: Annual KPIs (Matched to User Tone) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 chart-reveal">
        {/* Annual Sales YTD */}
        <div className="group relative bg-gradient-to-br from-[#0F172A] via-[#1e293b] to-[#1E3A8A] rounded-[24px] p-7 text-white overflow-hidden shadow-xl shadow-slate-900/20 hover:shadow-2xl hover:shadow-blue-900/40 transition-all duration-500 flex flex-col justify-between">
          
          {/* Decorative Glow */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/20 rounded-full blur-3xl pointer-events-none transform translate-x-1/3 -translate-y-1/3 group-hover:bg-blue-400/20 transition-colors duration-700" />
          
          <div className="relative z-10">
            {/* Header */}
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-full bg-white/10 backdrop-blur-md border border-white/10 flex items-center justify-center">
                  <DollarSign className="w-4 h-4 text-blue-200" />
                </div>
                <p className="text-[10px] font-bold text-blue-200 uppercase tracking-widest">Annual Sales (YTD)</p>
              </div>
              <div className="flex items-center gap-1.5 bg-white/10 backdrop-blur-md border border-white/10 px-2.5 py-1 rounded-lg shadow-sm">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                <span className="text-[10px] font-bold text-white">LIVE</span>
              </div>
            </div>

            {/* Middle KPI */}
            <h3 className="text-[2.25rem] xl:text-[2.75rem] font-black text-white tracking-tighter leading-none mb-2 transform group-hover:scale-[1.02] origin-left transition-transform duration-500">
              <Amt value={annualSalesExcHO} />
            </h3>
            <p className="text-[11px] text-blue-200/70 font-medium mb-6">
              Net sales generated by all boutiques excluding Head Office.
            </p>

            {/* Bottom Progress Block */}
            <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-[16px] p-4 mt-auto">
              <div className="flex items-end justify-between mb-3">
                <div>
                  <p className="text-[9px] font-black text-blue-200/80 uppercase tracking-widest mb-1">Achievement</p>
                  <div className="flex items-baseline gap-1.5">
                    <span className="text-xl font-black text-white">{fmtPct(annualAchievement)}</span>
                    <span className="text-[10px] text-blue-300 font-medium">of Target</span>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-[9px] text-blue-200/80 uppercase tracking-widest mb-1">Remaining</p>
                  <p className="text-xs font-bold text-white"><Amt value={Math.max(0, annualTarget - annualSalesExcHO)} compact /></p>
                </div>
              </div>
              
              {/* Progress Bar */}
              <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                <div 
                  className={cn(
                    "h-full rounded-full transition-all duration-1000",
                    annualAchievement >= 100 ? "bg-emerald-400" : "bg-blue-400"
                  )}
                  style={{ width: `${Math.min(annualAchievement, 100)}%` }}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Annual Target */}
        <div className="group relative bg-white rounded-[24px] p-7 border border-slate-200 overflow-hidden shadow-lg shadow-slate-200/50 hover:shadow-2xl hover:shadow-slate-200/80 transition-all duration-500 flex flex-col justify-between">
          {/* Blue Left Border Accent */}
          <div className="absolute left-0 top-6 bottom-6 w-1.5 bg-blue-600 rounded-r-full" />
          
          {/* Background Concentric Circles (Subtle) */}
          <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/4 w-96 h-96 pointer-events-none opacity-[0.02]">
            <div className="absolute inset-0 rounded-full border-[30px] border-slate-900" />
            <div className="absolute inset-[40px] rounded-full border-[30px] border-slate-900" />
            <div className="absolute inset-[80px] rounded-full border-[30px] border-slate-900" />
          </div>

          <div className="relative z-10">
            {/* Header */}
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center">
                  <Target className="w-4 h-4" />
                </div>
                <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Annual Target (Cumulative)</p>
              </div>
              <div className="flex items-center gap-1.5 bg-white border border-slate-200 px-2.5 py-1 rounded-lg shadow-sm">
                <Calendar className="w-3 h-3 text-blue-600" />
                <span className="text-[10px] font-bold text-slate-600">Jan – Dec</span>
              </div>
            </div>

            {/* Middle KPI */}
            <h3 className="text-[2.25rem] xl:text-[2.75rem] font-black text-[#0F172A] tracking-tighter leading-none mb-2">
              <Amt value={annualTarget} />
            </h3>
            <p className="text-[11px] text-slate-500 font-medium mb-5">
              Aggregated target for all stores (Excl. HO) for the selected year.
            </p>

            {/* Bottom Info Blocks */}
            <div className="bg-slate-50/80 border border-slate-100 rounded-[12px] p-3 flex items-center gap-4">
              {/* Block 1 */}
              <div className="flex items-center gap-3 flex-1">
                <div className="w-8 h-8 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                  <TrendingUp className="w-4 h-4" />
                </div>
                <div>
                  <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-0.5">Target Period</p>
                  <p className="text-xs font-black text-[#0F172A]">Jan – Dec {year}</p>
                </div>
              </div>
              
              {/* Divider */}
              <div className="w-[1px] h-8 bg-slate-200" />

              {/* Block 2 */}
              <div className="flex items-center gap-3 flex-1">
                <div className="w-8 h-8 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                  <FileText className="w-4 h-4" />
                </div>
                <div>
                  <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-0.5">Scoping</p>
                  <p className="text-xs font-black text-[#0F172A]">All Stores (Excl. HO)</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Row 1.5: Operational Metrics (Items & Transactions) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard 
          label="YTD Items Sold" 
          value={ytdQtyCurrent.toLocaleString('id-ID')}
          trendPct={ytdQtyPrevYear > 0 ? ((ytdQtyCurrent - ytdQtyPrevYear) / ytdQtyPrevYear) * 100 : 0}
          trendLabel="vs last year"
          icon={<Package className="w-6 h-6" />}
          colorClass="bg-[#eef2ff] text-[#4f46e5]"
          borderColor="border-t-[#4f46e5]"
          animationDelay="100ms"
        />
        <MetricCard 
          label="YTD Transactions" 
          value={ytdTxCurrent.toLocaleString('id-ID')}
          trendPct={ytdTxPrevYear > 0 ? ((ytdTxCurrent - ytdTxPrevYear) / ytdTxPrevYear) * 100 : 0}
          trendLabel="vs last year"
          icon={<ReceiptText className="w-6 h-6" />}
          colorClass="bg-[#f5f3ff] text-[#7c3aed]"
          borderColor="border-t-[#7c3aed]"
          animationDelay="200ms"
        />
        <MetricCard 
          label="Items Sold (MTD)" 
          value={mtdQtyCurrent.toLocaleString('id-ID')}
          trendPct={mtdQtyPrevMonth > 0 ? ((mtdQtyCurrent - mtdQtyPrevMonth) / mtdQtyPrevMonth) * 100 : 0}
          trendLabel="vs last month"
          icon={<Package className="w-6 h-6" />}
          colorClass="bg-[#eef2ff] text-[#4f46e5]"
          borderColor="border-t-transparent"
          animationDelay="300ms"
        />
        <MetricCard 
          label="Transactions (MTD)" 
          value={mtdTxCurrent.toLocaleString('id-ID')}
          trendPct={mtdTxPrevMonth > 0 ? ((mtdTxCurrent - mtdTxPrevMonth) / mtdTxPrevMonth) * 100 : 0}
          trendLabel="vs last month"
          icon={<ReceiptText className="w-6 h-6" />}
          colorClass="bg-[#f5f3ff] text-[#7c3aed]"
          borderColor="border-t-transparent"
          animationDelay="400ms"
        />
      </div>

      {/* Row 2: Monthly KPI Cards (Ultra Compact) */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">
        <div className="chart-reveal" style={{ animationDelay: '100ms' }}>
          <CompactCard
            label="Total Sales"
            value={<Amt value={totalNet} compact />}
            subLabel={totalNet > storeNetExcHO ? <><span>HO: </span><Amt value={totalNet - storeNetExcHO} compact /></> : 'Boutiques'}
            icon={<DollarSign className="w-3.5 h-3.5" />}
            color="blue"
            badge={
              <span className={cn(
                "text-[9px] font-black px-1.5 py-0.5 rounded ml-1 transition-all duration-500",
                momGrowthPct > 0 ? "bg-emerald-50 text-emerald-600 group-hover:bg-emerald-500 group-hover:text-white" : momGrowthPct < 0 ? "bg-rose-50 text-rose-600 group-hover:bg-rose-500 group-hover:text-white" : "bg-slate-100 text-slate-500"
              )}>
                {momGrowthPct > 0 ? '↑' : momGrowthPct < 0 ? '↓' : ''}{fmtPct(Math.abs(momGrowthPct))}
              </span>
            }
          />
        </div>

        <div className="chart-reveal" style={{ animationDelay: '200ms' }}>
          <CompactCard
            label="Store Sales"
            value={<Amt value={storeNetExcHO} compact />}
            icon={<BarChart2 className="w-3.5 h-3.5" />}
            color="indigo"
            badge={
              <span className={cn(
                "text-[9px] font-black px-1.5 py-0.5 rounded ml-1 transition-all duration-500",
                mtdGrowthPct > 0 ? "bg-emerald-50 text-emerald-600 group-hover:bg-emerald-500 group-hover:text-white" : mtdGrowthPct < 0 ? "bg-rose-50 text-rose-600 group-hover:bg-rose-500 group-hover:text-white" : "bg-slate-100 text-slate-500"
              )}>
                {mtdGrowthPct > 0 ? '+' : ''}{fmtPct(mtdGrowthPct)}
              </span>
            }
          />
        </div>

        <div className="chart-reveal" style={{ animationDelay: '300ms' }}>
          <CompactCard 
            label="Achievement" 
            value={fmtPct(achievement)}
            icon={<Target className="w-3.5 h-3.5" />}
            color={achievement >= 100 ? "emerald" : achievement >= 80 ? "amber" : "rose"}
            valueClassName={achievement >= 100 ? "text-emerald-600" : achievement >= 80 ? "text-amber-500" : "text-rose-600"}
          />
        </div>

        <div className="chart-reveal" style={{ animationDelay: '400ms' }}>
          <CompactCard 
            label="Cost %" 
            value={fmtPct(costPercentage)}
            subLabel={<Amt value={totalCost} compact />}
            icon={<Percent className="w-3.5 h-3.5" />}
            color={costPercentage > 15 ? "rose" : "slate"}
            info="Cost % = (Disc + Comm) / Gross"
          />
        </div>

        <div className="chart-reveal" style={{ animationDelay: '500ms' }}>
          <CompactCard 
            label="Avg Disc %" 
            value={fmtPct(avgDiscountPercentage)}
            subLabel={<Amt value={totalValDisc} compact />}
            icon={<CreditCard className="w-3.5 h-3.5" />}
            color={avgDiscountPercentage > 12 ? "amber" : "slate"}
            info="Total Disc / Total Gross"
          />
        </div>
      </div>
    </div>
  );
}

function CompactCard({ label, value, subLabel, icon, color, badge, valueClassName, info }: any) {
  const colorClasses: any = {
    blue: "bg-blue-50 text-blue-600",
    indigo: "bg-indigo-50 text-indigo-600",
    emerald: "bg-emerald-50 text-emerald-600",
    amber: "bg-amber-50 text-amber-600",
    rose: "bg-rose-50 text-rose-600",
    slate: "bg-slate-100 text-slate-500",
  };

  return (
    <div className="group relative bg-white border border-slate-200 p-4 rounded-2xl hover:border-blue-300 hover:shadow-xl hover:shadow-blue-500/10 hover:-translate-y-1.5 transition-all duration-500 ease-out cursor-default hover:z-50">
      {/* Shine effect isolated to prevent tooltip clipping */}
      <div className="absolute inset-0 rounded-2xl overflow-hidden pointer-events-none">
        <div className="absolute inset-0 -translate-x-[150%] bg-gradient-to-r from-transparent via-white/80 to-transparent group-hover:translate-x-[150%] transition-transform duration-1000 ease-in-out z-10 mix-blend-overlay" />
      </div>
      
      <div className="flex items-start justify-between mb-2 relative z-10">
        <div className={cn("w-7 h-7 rounded-lg flex items-center justify-center transition-all duration-500 group-hover:scale-110 group-hover:rotate-6 group-hover:shadow-md", colorClasses[color] || colorClasses.slate)}>
          {icon}
        </div>
        {info && (
          <div className="group/info relative flex justify-center">
            <Info className="w-3.5 h-3.5 text-slate-300 cursor-help" />
            <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-32 bg-slate-800 text-white text-[9px] px-2.5 py-2 rounded-lg shadow-2xl invisible opacity-0 group-hover/info:visible group-hover/info:opacity-100 transition-all duration-300 z-[100] text-center pointer-events-none">
              {info}
              {/* Tooltip Arrow */}
              <div className="absolute top-full left-1/2 -translate-x-1/2 border-[5px] border-transparent border-t-slate-800" />
            </div>
          </div>
        )}
      </div>
      
      <div className="relative z-10">
        <div className="flex items-center justify-between gap-1 mb-0.5">
          <p className="text-[9px] font-black text-slate-400 uppercase tracking-wider truncate">{label}</p>
          {badge}
        </div>
        <h3 className={cn("text-base font-black text-slate-900 tracking-tight", valueClassName)}>
          {value}
        </h3>
        {subLabel && <p className="text-[9px] text-slate-400 font-bold leading-none mt-1">{subLabel}</p>}
      </div>
    </div>
  );
}

function MetricCard({ label, value, trendPct, trendLabel, icon, colorClass, borderColor, animationDelay }: any) {
  return (
    <div className={cn("group bg-white border-x border-b border-t-[3px] border-slate-200 rounded-2xl p-5 shadow-sm hover:shadow-xl hover:shadow-blue-500/5 hover:-translate-y-1.5 transition-all duration-500 ease-out chart-reveal", borderColor)} style={{ animationDelay }}>
      <div className="flex items-center gap-5">
        <div className={cn("w-14 h-14 rounded-[14px] flex items-center justify-center transition-all duration-500 group-hover:scale-110 group-hover:rotate-3", colorClass)}>
          {icon}
        </div>
        <div className="flex flex-col">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{label}</p>
          <h3 className="text-[1.35rem] font-black text-slate-900 leading-none tracking-tight mb-1.5">{value}</h3>
          <div className="flex items-center gap-1.5">
            <span className={cn("text-[11px] font-black flex items-center", trendPct >= 0 ? "text-emerald-500" : "text-rose-500")}>
              {trendPct >= 0 ? '↗' : '↘'} {Math.abs(trendPct).toFixed(1)}%
            </span>
            <span className="text-[10px] font-bold text-slate-400">{trendLabel}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
