-- Create stock_store table
CREATE TABLE IF NOT EXISTS stock_store (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  location TEXT NOT NULL,
  category TEXT NOT NULL,
  jan INTEGER DEFAULT 0,
  feb INTEGER DEFAULT 0,
  mar INTEGER DEFAULT 0,
  apr INTEGER DEFAULT 0,
  may INTEGER DEFAULT 0,
  jun INTEGER DEFAULT 0,
  jul INTEGER DEFAULT 0,
  aug INTEGER DEFAULT 0,
  sep INTEGER DEFAULT 0,
  oct INTEGER DEFAULT 0,
  nov INTEGER DEFAULT 0,
  dec INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(year, location, category)
);

-- Enable RLS
ALTER TABLE stock_store ENABLE ROW LEVEL SECURITY;

-- Allow anon read
CREATE POLICY "Allow anon read stock_store" ON stock_store
  FOR SELECT TO anon USING (true);

-- Allow anon all (for testing/sync)
CREATE POLICY "Allow anon all stock_store" ON stock_store
  FOR ALL TO anon USING (true) WITH CHECK (true);
